### ISSUE TITLE
Integrated modules sometimes give Enterprise license warning. (Beta or bought) License has to be in enviroment vars.to avoid.

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/universal-automation#25]
#### Describe the Issue

Integrated modules sometimes give Enterprise license warning. (Beta or bought) License has to be in enviroment vars.to avoid.

#### To Reproduce

Steps to reproduce the behavior: (Example)

Run UD\UA dashboard and see error.

#### Expected behavior

Shouldn't show error. This is problably just a problem with the UA beta but we should fix it. 

#### Script Sample

Attempt to attach sample code that will allow others to reproduce the issue. **NOTE**: Generally speaking this is the **MOST EFFECTIVE** way to have your issue resolved.

#### Version Information

- **Host Operating System**:
- **Host PowerShell Version**:
- **Universal Automation Version**:
- **Universal Dashboard Version**:
- **UD Hosting Method**: (Powershell, IIS, App Service, Etc.)

**Comment by Windos** [comment]
@adamdriscoll / @leeberg I am seeing this issue in recent beta builds consistently. It's been a while since I've been able to test things, but I believe I was seeing it on beta5 and have just updated to beta6 and still see it.

I get an error about needing a UD Enterprise license when importing the UA.Dashboard module:

![image](https://user-images.githubusercontent.com/6955786/73795882-95e96900-4810-11ea-8773-35239f1dbe3f.png)

**Comment by adamdriscoll** [comment]
Strange. I'll look into it today. You shouldn't need a license to import that module....

**Comment by adamdriscoll** [comment]
We've totally redone the dashboard for v1.1. This won't be a problem any more.
